[default_install]
Windows = [
    'C:/Program Files/FreeCAD 1.0/bin',
    'C:/Program Files/FreeCAD/bin',
]

[folders]
install_dir = [
    "FreeCAD 1.0",
    "FreeCAD",
]

[sql]
[sql.table_types]
listed_uniques = '''
CREATE TABLE IF NOT EXISTS {name} (
    {columns},
    UNIQUE ({uniques})
)
''' # A table requiring a list of columns and a list of unique columns

# Object Info Tables
[sql.tables.FreecadObjectInfo]
type = 'listed_uniques'
unique = ['FileUid', 'name', 'id']
[sql.tables.FreecadObjectInfo.columns]
FileUid = 'UUID'
name = 'TEXT'
id = 'INTEGER'
type = 'TEXT'
Label = 'TEXT'
Label2 = 'TEXT'
Visibility = 'BOOLEAN'

[sql.tables.FreecadSketchGeometryInfo]
type = 'listed_uniques'
unique = ['FileUid', 'SketchName', 'ListName', 'ListIndex', 'id']
[sql.tables.FreecadSketchGeometryInfo.columns]
FileUid = 'UUID'
SketchName = 'TEXT'
ListName = 'TEXT'
ListIndex = 'INTEGER'
type = 'TEXT'
id = 'INTEGER'
migrated = 'INTEGER'
internalGeometryType = 'INTEGER'
Construction = 'BOOLEAN'

[sql.tables.FreecadObjectDependencies]
type = 'listed_uniques'
unique = ['FileUid', 'Object', 'Dependency']
[sql.tables.FreecadObjectDependencies.columns]
FileUid = 'UUID'
Object = 'TEXT'
Dependency = 'TEXT'

# Sketch Elements Tables
[sql.tables.FreecadConstraint]
type = 'listed_uniques'
unique = ['FileUid', 'SketchName', 'ListName', 'ListIndex']
[sql.tables.FreecadConstraint.columns]
FileUid = 'UUID'
SketchName = 'TEXT'
ListName = 'TEXT'
ListIndex = 'INTEGER'
Name = 'TEXT'
Type = 'INTEGER'
InternalAlignmentType = 'INTEGER'
InternalAlignmentIndex = 'INTEGER'
First = 'INTEGER'
FirstPos = 'INTEGER'
Second = 'INTEGER'
SecondPos = 'INTEGER'
Third = 'INTEGER'
ThirdPos = 'INTEGER'
Value = 'REAL'
LabelDistance = 'REAL'
LabelPosition = 'REAL'
IsDriving = 'BOOLEAN'
IsInVirtualSpace = 'BOOLEAN'
IsActive = 'BOOLEAN'

[sql.tables.FreecadArcOfCircle]
type = 'listed_uniques'
unique = ['FileUid', 'SketchName', 'ListName', 'id']
freecad_geometry_type = 'Part::GeomArcOfCircle'
[sql.tables.FreecadArcOfCircle.columns]
FileUid = 'UUID'
SketchName = 'TEXT'
ListName = 'TEXT'
id = 'INTEGER'
CenterX = 'REAL'
CenterY = 'REAL'
CenterZ = 'REAL'
NormalX = 'REAL'
NormalY = 'REAL'
NormalZ = 'REAL'
AngleXU = 'REAL'
Radius = 'REAL'
StartAngle = 'REAL'
EndAngle = 'REAL'

[sql.tables.FreecadLineSegment]
type = 'listed_uniques'
unique = ['FileUid', 'SketchName', 'ListName', 'id']
freecad_geometry_type = 'Part::GeomLineSegment'
[sql.tables.FreecadLineSegment.columns]
FileUid = 'UUID'
SketchName = 'TEXT'
ListName = 'TEXT'
id = 'INTEGER'
StartX = 'REAL'
StartY = 'REAL'
StartZ = 'REAL'
EndX = 'REAL'
EndY = 'REAL'
EndZ = 'REAL'

[sql.tables.FreecadPoint]
type = 'listed_uniques'
unique = ['FileUid', 'SketchName', 'ListName', 'id']
freecad_geometry_type = 'Part::GeomPoint'
[sql.tables.FreecadPoint.columns]
FileUid = 'UUID'
SketchName = 'TEXT'
ListName = 'TEXT'
id = 'INTEGER'
X = 'REAL'
Y = 'REAL'
Z = 'REAL'

[sql.tables.FreecadCircle]
type = 'listed_uniques'
unique = ['FileUid', 'SketchName', 'ListName', 'id']
freecad_geometry_type = 'Part::GeomCircle'
[sql.tables.FreecadCircle.columns]
FileUid = 'UUID'
SketchName = 'TEXT'
ListName = 'TEXT'
id = 'INTEGER'
CenterX = 'REAL'
CenterY = 'REAL'
CenterZ = 'REAL'
NormalX = 'REAL'
NormalY = 'REAL'
NormalZ = 'REAL'
AngleXU = 'REAL'
Radius = 'REAL'

[sql.tables.FreecadEllipse]
type = 'listed_uniques'
unique = ['FileUid', 'SketchName', 'ListName', 'id']
freecad_geometry_type = 'Part::GeomEllipse'
[sql.tables.FreecadEllipse.columns]
FileUid = 'UUID'
SketchName = 'TEXT'
ListName = 'TEXT'
id = 'INTEGER'
CenterX = 'REAL'
CenterY = 'REAL'
CenterZ = 'REAL'
NormalX = 'REAL'
NormalY = 'REAL'
NormalZ = 'REAL'
MajorRadius = 'REAL'
MinorRadius = 'REAL'
AngleXU = 'REAL'