# Contains settings for pancad sqlite databases

[conform_type]
# type names for conformed pancad objects put into a database
Point = "Point"
Circle = "Circle"
CircularArc = "CircularArc"
Ellipse = "Ellipse"
Line = "Line"
LineSegment = "Line_segment"
Plane = "Plane"
CoordinateSystem = "CoordinateSystem"